env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

language: php

matrix:
  include:
    - php: "7.0"
      env: TYPO3_VERSION="^8.7" AIMEOS_VERSION="^18" ADMIN_PANEL="typo3/cms-core:^8.7" COVERAGE="NO"
    - php: "7.1"
      env: TYPO3_VERSION="^8.7" AIMEOS_VERSION="^18" ADMIN_PANEL="typo3/cms-core:^8.7" COVERAGE="NO"
    - php: "7.2"
      env: TYPO3_VERSION="^8.7" AIMEOS_VERSION="^19" ADMIN_PANEL="typo3/cms-core:^8.7" COVERAGE="NO"
    - php: "7.2"
      env: TYPO3_VERSION="^9.5" AIMEOS_VERSION="^18" ADMIN_PANEL="typo3/cms-adminpanel:^9.5" COVERAGE="NO"
    - php: "7.3"
      env: TYPO3_VERSION="^9.5" AIMEOS_VERSION="^19" ADMIN_PANEL="typo3/cms-adminpanel:^9.5" COVERAGE="NO"
    - php: "7.4"
      env: TYPO3_VERSION="^9.5" AIMEOS_VERSION="^20" ADMIN_PANEL="typo3/cms-adminpanel:^9.5" COVERAGE="NO"
    - php: "7.2"
      env: TYPO3_VERSION="^10.4" AIMEOS_VERSION="^19" ADMIN_PANEL="typo3/cms-adminpanel:^10.4" COVERAGE="NO"
    - php: "7.3"
      env: TYPO3_VERSION="^10.4" AIMEOS_VERSION="^20" ADMIN_PANEL="typo3/cms-adminpanel:^10.4" COVERAGE="NO"
    - php: "7.4"
      env: TYPO3_VERSION="^10.4" AIMEOS_VERSION="^20" ADMIN_PANEL="typo3/cms-adminpanel:^10.4" COVERAGE="YES"

install:
  - composer require --no-update "typo3/cms-core:$TYPO3_VERSION"
  - composer require --no-update "aimeos/aimeos-typo3:$AIMEOS_VERSION"
  - composer require --no-update "$ADMIN_PANEL"
  - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - if [[ "$COVERAGE" != "NO" ]]; then ./vendor/bin/phpunit -c Build/phpunit.xml --coverage-text --coverage-clover build/logs/clover.xml; fi
