config_version = "0"

exclude_patterns = [
    "**/Private/krexx/resources/**",
    "**/Private/Layouts/**",
    "**/Private/Partials/**",
    "**/Private/Templates/**",
]

test_patterns = [
  "**/Tests/**",
  "**/tests/**",
]

[runtimes.enabled]
php = "7.4"

[smells]
mode = "comment"

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "checkov"

[[plugin]]
name = "markdownlint"
mode = "comment"

[[plugin]]
name = "ripgrep"
mode = "comment"

[[plugin]]
name = "trivy"
drivers = [
  "config",
  "fs-vuln"
]

[[plugin]]
name = "trufflehog"