name: Build

on:
  push:
    branches: [ master, develop, feature/*]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        what: [ 't38php70', 't38php71', 't39php72', 't39php73', 't310php74' ]
        # what: [ 't38php70', 't38php71', 't39php72', 't39php73', 't310php74', 't311php80' ]

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP 7.0
      uses: shivammathur/setup-php@v2
      if: ${{ matrix.what == 't38php70' }}
      with:
        php-version: '7.0'

    - name: Install PHP 7.1
      uses: shivammathur/setup-php@v2
      if: ${{ matrix.what == 't38php71' }}
      with:
        php-version: '7.1'

    - name: Install PHP 7.2
      uses: shivammathur/setup-php@v2
      if: ${{ matrix.what == 't39php72' }}
      with:
        php-version: '7.2'

    - name: Install PHP 7.3
      uses: shivammathur/setup-php@v2
      if: ${{ matrix.what == 't39php73' }}
      with:
        php-version: '7.3'

    - name: Install PHP 7.4
      uses: shivammathur/setup-php@v2
      if: ${{ matrix.what == 't310php74' ||  matrix.what == 't311php74' }}
      with:
        php-version: '7.4'

    - name: Install PHP 8.0
      uses: shivammathur/setup-php@v2
      if: ${{ matrix.what == 't311php80' }}
      with:
        php-version: '8.0'

    - name: Make sure we are using composer v1
      run: |
        sudo composer self-update --1
        sudo chown $USER $HOME/.composer

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install TYPO3 8
      run: composer require --no-update "typo3/cms-core:^8.7"
      if: ${{ matrix.what == 't38php70' || matrix.what == 't38php71' }}

    - name: Install TYPO3 9
      run: composer require --no-update "typo3/cms-core:^9.5"
      if: ${{ matrix.what == 't39php72' || matrix.what == 't39php73' }}

    - name: Install TYPO3 10
      run: composer require --no-update "typo3/cms-core:^10.4"
      if: ${{ matrix.what == 't310php74' }}

    - name: Install TYPO3 11
      run: composer require --no-update "typo3/cms-core:^11"
      if: ${{ matrix.what == 't311php80' }}

    - name: Install Aimeos 18
      run: composer require --no-update "aimeos/aimeos-typo3:^18"
      if: ${{ matrix.what == 't38php70' || matrix.what == 't39php72' }}

    - name: Install Aimeos 19
      run: composer require --no-update "aimeos/aimeos-typo3:^19"
      if: ${{ matrix.what == 't38php71' }}

    - name: Install Aimeos 20
      run: composer require --no-update "aimeos/aimeos-typo3:^20"
      if: ${{ matrix.what == 't39php73' }}

    - name: Install Aimeos 21
      run: composer require --no-update "aimeos/aimeos-typo3:^21"
      if: ${{ matrix.what == 't310php74' }}

    - name: Remove Aimeos
      run: composer remove --dev --no-update "aimeos/aimeos-typo3"
      if: ${{ matrix.what == 't311php80' }}

    - name: Install Admin Panel 9
      run: composer require --no-update "typo3/cms-adminpanel:^9.5"
      if: ${{ matrix.what == 't39php72' }}

    - name: Install Admin Panel 10
      run: composer require --no-update "typo3/cms-adminpanel:^10.4"
      if: ${{ matrix.what == 't310php74' }}

    - name: Install Admin Panel 11
      run: composer require --no-update "typo3/cms-adminpanel:^11"
      if: ${{ matrix.what == 't311php80' }}

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer packages
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Build
      run: composer test

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      if: ${{ matrix.what == 't310php74' }}
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATEKEY }}
