name: Build

on:
  push:
    branches: [ master, develop, feature/*]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { php: 7.0, composer: 1, TYPO3: ^8.7,  Aimeos: ^18}
          - { php: 7.1, composer: 1, TYPO3: ^8.7,  Aimeos: ^19}
          - { php: 7.2, composer: 1, TYPO3: ^9.5,  Aimeos: ^19}
          - { php: 7.3, composer: 1, TYPO3: ^9.5,  Aimeos: ^20}
          - { php: 7.3, composer: 1, TYPO3: ^10.4, Aimeos: ^20}
          - { php: 7.4, composer: 1, TYPO3: ^10.4, Aimeos: ^21}
          - { php: 7.4, composer: 2, TYPO3: ^11.5, Aimeos: ^21}
          - { php: 8.0, composer: 2, TYPO3: ^11.5, Aimeos: ^21}

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.env.php }}

    - name: Update Composer
      run: |
        sudo composer self-update --${{ matrix.env.composer }}
        sudo chown $USER $HOME/.composer

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install TYPO3
      run: composer require --no-update "typo3/cms-core:${{ matrix.env.TYPO3 }}"

    - name: Install Aimeos
      run: composer require --no-update "aimeos/aimeos-typo3:${{ matrix.env.Aimeos }}"

    - name: Install Admin Panel
      run: composer require --no-update "typo3/cms-adminpanel:${{ matrix.env.TYPO3 }}"
      if: ${{ matrix.env.TYPO3 != '^8.7' }}

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer packages
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Build
      run: composer test

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      if: ${{ matrix.env.php == 7.4 }}
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATEKEY }}
