name: Build

on:
  push:
    branches: [ main, develop, feature/*]
  pull_request:
    branches: [ main ]

permissions: read-all

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { php: 7.4, TYPO3: ^10.4, Aimeos: ^21, CodeClimate: no  }
          - { php: 8.0, TYPO3: ^11.5, Aimeos: ^21, CodeClimate: no  }
          - { php: 8.1, TYPO3: ^11.5, Aimeos: ^22, CodeClimate: no  }
          - { php: 8.2, TYPO3: ^11.5, Aimeos: ^22, CodeClimate: no  }
          - { php: 8.1, TYPO3: ^12.4, Aimeos: ^23, CodeClimate: no  }
          - { php: 8.2, TYPO3: ^12.4, Aimeos: ^23, CodeClimate: no  }
          - { php: 8.3, TYPO3: ^12.4, Aimeos: ^24, CodeClimate: no  }
          - { php: 8.3, TYPO3: ^13.4, Aimeos: ^24, CodeClimate: no  }
          - { php: 8.4, TYPO3: ^13.4, Aimeos: ^24, CodeClimate: yes }

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.env.php }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install TYPO3
      run: composer require --no-update "typo3/cms-core:${{ matrix.env.TYPO3 }}"

    - name: Install Aimeos
      run: composer require --no-update "aimeos/aimeos-typo3:${{ matrix.env.Aimeos }}"
      if: ${{ matrix.env.Aimeos != 'no' }}

    - name: Remove ContentBlocks
      run: composer remove --no-update "friendsoftypo3/content-blocks"
      if: matrix.env.TYPO3 != '^13.4' }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Build without coverage
      if: ${{ matrix.env.CodeClimate == 'no' }}
      run: composer test

    - name: Build
      if: ${{ matrix.env.CodeClimate == 'yes' }}
      run: composer test-coverage

    - name: Publish code coverage
      uses: qltysh/qlty-action/coverage@v1
      if: ${{ matrix.env.CodeClimate == 'yes' }}
      with:
        token: ${{secrets.QLTY_COVERAGE_TOKEN}}
        files: clover.xml
